### ISSUE TITLE
Compile issue with VS2017 project, of v0.11.0

### ISSUE THREAD

**Issue by harryhow** [pierrep/ofxGifImage#1]
I have a project generated by oF's (v0.11.0) project generator and also including ofxGifImage plugin only. However there are compile errors mostly coming from wglew.h when trying to compile ofxGifImage.cpp. 

Any thoughts/solution for this? 
Thanks!

**Comment by pierrep** [comment]
Thanks for reporting. Seems like the FreeImage.h header needed to be included after ofMain.h on Windows.
Can you get the latest code and see if that fixes things for you?

**Comment by harryhow** [comment]
Yes, this issue fixed if I switch the include header file sequence. It works, thanks @pierrep for your great help. : )
