### ISSUE TITLE
Memory leak issue and quick fix

### ISSUE THREAD

**Issue by harryhow** [pierrep/ofxGifImage#3]
Found a memory leak issue that causes app crashed after loading GIF files for multiple times.
Quick fix will be adding following lines under decodeFrame() of  ofxGifImage.cpp after frames.push_back(frame);
```
FreeImage_Unload(bmp)
pix.clear();
```
I don't have full understanding of the whole project, it's just a quick fix though.

**Comment by pierrep** [comment]
Thanks for that, I'll investigate. To be honest I haven't used this addon in production code yet so it hasn't been stress tested...but I'm keen to clean it up, so the bug reports are useful.

**Comment by pierrep** [comment]
I ran the app through a leak checker and there definitely was a leak. I also found another small memory cleanup issue. I've pushed the changes to master. You don't need to clear the pix variable, it gets automatically cleared up each frame.
