### ISSUE TITLE
getHeight() get the width & getWidth() get the height

### ISSUE THREAD

**Issue by Taprik** [pierrep/ofxGifImage#5]
Dear Pierrep,
First congratulations for this addon.
You rule man !

It's a detail but this part is not correct I guess
`//-----------------------------------------------------------------------
float ofxGifImage::getWidth() const
{
    return height;
}

//-----------------------------------------------------------------------
float ofxGifImage::getHeight() const
{
    return width;
}`

Cheers

**Comment by pierrep** [comment]
Haha, thanks for the compliment. I just used this addon last weekend for my son's birthday - an automated GIF portrait machine. They loved it.
Thanks for the bug report, this looks very wrong and is very embarrassing. It must have been late at night, lol
