### ISSUE TITLE
Playing from start doesn't reset lastDrawn time

### ISSUE THREAD

**Issue by rjx-ray** [pierrep/ofxGifImage#6]
Firstly basic operation is great,  animated  gifs are played flawlessly.

However, for our use case we only want the gif to play when the mouse is over it. Ok, I can stop or  pause playing but when I restart  it races through the animation showing a new frame for every draw until it catches up with the last time it played. This could be a very long time.

https://github.com/pierrep/ofxGifImage/assets/24891831/126a7459-4ab8-44b3-81fe-a80690097522

The problem is that there is a lastDrawn time as part of the class. If the current time minus the lastDrawn time is greater than the lastDrawn time it increments the frameIndex for the draw. But then it only increments the lastDrawn time by the frame's duration so it's incrementing every draw until that catches up with the current time.

What I would really like would be to have a public way of resetting the last drawn time.

It seems rational to me that playFromStart should do this
`void playFromStart() {bIsPlaying = true; frameIndex = 0; lastDrawn = 0;}`

But if that's not acceptable a resetLastDraw function would be OK.

Could you consider making this change, it seems an overkill to fork just for this issue.

Thanks

**Comment by pierrep** [comment]
Hi,
Thanks for this!
I've added lastDrawn = 0 in playFromStart(). This is why getting other people to use your code is useful!

**Comment by rjx-ray** [comment]
Thanks!

**Comment by rjx-ray** [comment]
**But there is a bug in your fix - there has to be a semicolon after lastDrawn = 0 in playFromStart**

**Comment by pierrep** [comment]
Sorry done...I  should have requested a PR,, I'm unable to test directly at the moment!

**Comment by rjx-ray** [comment]
No problem, thanks very much for the quick response
